export const TARGETS = [
    { id: 'vercel', domain: 'vercel.com' }, { id: 'stripe', domain: 'stripe.com' }, { id: 'figma', domain: 'figma.com' },
    { id: 'openai', domain: 'openai.com' }, { id: 'anthropic', domain: 'anthropic.com' }, { id: 'uber', domain: 'uber.com' },
    { id: 'airbnb', domain: 'airbnb.com' }, { id: 'roblox', domain: 'roblox.com' }, { id: 'snapchat', domain: 'snap.com' },
    { id: 'discord', domain: 'discord.com' }, { id: 'atlassian', domain: 'atlassian.com' }, { id: 'datadog', domain: 'datadoghq.com' },
    { id: 'pinterest', domain: 'pinterest.com' }, { id: 'shopify', domain: 'shopify.com' }, { id: 'instacart', domain: 'instacart.com' },
    { id: 'doordash', domain: 'doordash.com' }, { id: 'lyft', domain: 'lyft.com' }, { id: 'reddit', domain: 'reddit.com' },
    { id: 'dropbox', domain: 'dropbox.com' }, { id: 'zoom', domain: 'zoom.us' }, { id: 'hashicorp', domain: 'hashicorp.com' },
    { id: 'grafana', domain: 'grafana.com' }, { id: 'github', domain: 'github.com' }, { id: 'gitlab', domain: 'about.gitlab.com' },
    { id: 'confluent', domain: 'confluent.io' }, { id: 'mongodb', domain: 'mongodb.com' }, { id: 'cockroachlabs', domain: 'cockroachlabs.com' },
    { id: 'sentry', domain: 'sentry.io' }, { id: 'postman', domain: 'postman.com' }, { id: 'circleci', domain: 'circleci.com' },
    { id: 'auth0', domain: 'auth0.com' }, { id: 'okta', domain: 'okta.com' }, { id: 'fastly', domain: 'fastly.com' },
    { id: 'cloudflare', domain: 'cloudflare.com' }, { id: 'elastic', domain: 'elastic.co' }, { id: 'digitalocean', domain: 'digitalocean.com' },
    { id: 'netlify', domain: 'netlify.com' }, { id: 'supabase', domain: 'supabase.com' }, { id: 'planetscale', domain: 'planetscale.com' },
    { id: 'checkly', domain: 'checklyhq.com' }, { id: 'monzo', domain: 'monzo.com' }, { id: 'revolut', domain: 'revolut.com' },
    { id: 'robinhood', domain: 'robinhood.com' }, { id: 'coinbase', domain: 'coinbase.com' }, { id: 'kraken', domain: 'kraken.com' },
    { id: 'chime', domain: 'chime.com' }, { id: 'plaid', domain: 'plaid.com' }, { id: 'brex', domain: 'brex.com' },
    { id: 'ramp', domain: 'ramp.com' }, { id: 'bolt', domain: 'bolt.com' }, { id: 'affirm', domain: 'affirm.com' },
    { id: 'klarna', domain: 'klarna.com' }, { id: 'sofi', domain: 'sofi.com' }, { id: 'gusto', domain: 'gusto.com' },
    { id: 'carta', domain: 'carta.com' }, { id: 'wealthfront', domain: 'wealthfront.com' }, { id: 'betterment', domain: 'betterment.com' },
    { id: 'circle', domain: 'circle.com' }, { id: 'chainlink', domain: 'chain.link' }, { id: 'ripple', domain: 'ripple.com' },
    { id: 'linear', domain: 'linear.app' }, { id: 'notion', domain: 'notion.so' }, { id: 'slack', domain: 'slack.com' },
    { id: 'asana', domain: 'asana.com' }, { id: 'monday', domain: 'monday.com' }, { id: 'miro', domain: 'miro.com' },
    { id: 'canva', domain: 'canva.com' }, { id: 'loom', domain: 'loom.com' }, { id: 'grammarly', domain: 'grammarly.com' },
    { id: 'zapier', domain: 'zapier.com' }, { id: 'calendly', domain: 'calendly.com' }, { id: 'intercom', domain: 'intercom.com' },
    { id: 'hubspot', domain: 'hubspot.com' }, { id: 'zendesk', domain: 'zendesk.com' }, { id: 'box', domain: 'box.com' },
    { id: 'airtable', domain: 'airtable.com' }, { id: 'webflow', domain: 'webflow.com' }, { id: 'framer', domain: 'framer.com' },
    { id: 'ghost', domain: 'ghost.org' }, { id: 'substack', domain: 'substack.com' }, { id: 'huggingface', domain: 'huggingface.co' },
    { id: 'scale', domain: 'scale.com' }, { id: 'anduril', domain: 'anduril.com' }, { id: 'spacex', domain: 'spacex.com' },
    { id: 'tesla', domain: 'tesla.com' }, { id: 'rivian', domain: 'rivian.com' }, { id: 'neuralink', domain: 'neuralink.com' },
    { id: 'cruisecareers', domain: 'getcruise.com' }, { id: 'waymo', domain: 'waymo.com' }, { id: 'aurora', domain: 'aurora.tech' },
    { id: 'warbyparker', domain: 'warbyparker.com' }, { id: 'casper', domain: 'casper.com' }, { id: 'allbirds', domain: 'allbirds.com' },
    { id: 'peloton', domain: 'onepeloton.com' }, { id: 'hellofresh', domain: 'hellofresh.com' }, { id: 'glossier', domain: 'glossier.com' },
    { id: 'stockx', domain: 'stockx.com' }, { id: 'goat', domain: 'goat.com' }, { id: 'seatgeek', domain: 'seatgeek.com' },
    { id: 'ticketmaster', domain: 'ticketmaster.com' }, { id: 'perplexity', domain: 'perplexity.ai' }, { id: 'mistral', domain: 'mistral.ai' },
    { id: 'cohere', domain: 'cohere.com' }, { id: 'characterai', domain: 'character.ai' }, { id: 'pika', domain: 'pika.art' },
    { id: 'runway', domain: 'runwayml.com' }, { id: 'elevenlabs', domain: 'elevenlabs.io' }, { id: 'copyai', domain: 'copy.ai' },
    { id: 'jasper', domain: 'jasper.ai' }, { id: 'glean', domain: 'glean.com' }, { id: 'tome', domain: 'tome.app' },
    { id: 'poe', domain: 'poe.com' }, { id: 'chainalysis', domain: 'chainalysis.com' }, { id: 'fireblocks', domain: 'fireblocks.com' },
    { id: 'ledger', domain: 'ledger.com' }, { id: 'alchemy', domain: 'alchemy.com' }, { id: 'moonpay', domain: 'moonpay.com' },
    { id: 'dapperlabs', domain: 'dapperlabs.com' }, { id: 'consensys', domain: 'consensys.io' }, { id: 'gemini', domain: 'gemini.com' },
    { id: 'anchorage', domain: 'anchorage.com' }, { id: 'deel', domain: 'deel.com' }, { id: 'remote', domain: 'remote.com' },
    { id: 'melio', domain: 'melio.com' }, { id: 'tiptop', domain: 'tiptop.com' }, { id: 'replit', domain: 'replit.com' },
    { id: 'railway', domain: 'railway.app' }, { id: 'neon', domain: 'neon.tech' }, { id: 'clerk', domain: 'clerk.com' },
    { id: 'resend', domain: 'resend.com' }, { id: 'turso', domain: 'turso.tech' }, { id: 'upstash', domain: 'upstash.com' },
    { id: 'axiom', domain: 'axiom.co' }, { id: 'flyio', domain: 'fly.io' }, { id: 'temporal', domain: 'temporal.io' },
    { id: 'tailscale', domain: 'tailscale.com' }, { id: 'docker', domain: 'docker.com' }, { id: 'buoyant', domain: 'buoyant.io' },
    { id: 'miztiq', domain: 'miztiq.com' }, { id: 'pulumi', domain: 'pulumi.com' }, { id: 'clickup', domain: 'clickup.com' },
    { id: 'descript', domain: 'descript.com' }, { id: 'typeform', domain: 'typeform.com' }, { id: 'pitch', domain: 'pitch.com' },
    { id: 'front', domain: 'front.com' }, { id: 'gong', domain: 'gong.io' }, { id: 'drift', domain: 'drift.com' },
    { id: 'wiz', domain: 'wiz.io' }, { id: 'snyk', domain: 'snyk.io' }, { id: 'lacework', domain: 'lacework.com' },
    { id: 'twingate', domain: 'twingate.com' }, { id: 'drata', domain: 'drata.com' }, { id: 'vanta', domain: 'vanta.com' },
    { id: 'oneidentity', domain: 'oneidentity.com' }, { id: 'faire', domain: 'faire.com' }, { id: 'whatnot', domain: 'whatnot.com' },
    { id: 'deliveryhero', domain: 'deliveryhero.com' }, { id: 'blueapron', domain: 'blueapron.com' }, { id: 'snowflake', domain: 'snowflake.com' },
    { id: 'databricks', domain: 'databricks.com' }, { id: 'dbtlabs', domain: 'getdbt.com' }, { id: 'fivetran', domain: 'fivetran.com' },
    { id: 'starburst', domain: 'starburst.io' }, { id: 'airbyte', domain: 'airbyte.com' }, { id: 'amplitude', domain: 'amplitude.com' },
    { id: 'segment', domain: 'segment.com' }, { id: 'braze', domain: 'braze.com' }, { id: 'relativityspace', domain: 'relativityspace.com' },
    { id: 'zookscareers', domain: 'zoox.com' }, { id: 'nuro', domain: 'nuro.ai' }, { id: 'skydio', domain: 'skydio.com' },
    { id: 'verkada', domain: 'verkada.com' }, { id: 'samsara', domain: 'samsara.com' }, { id: 'framework', domain: 'frame.work' },
    { id: 'twitch', domain: 'twitch.tv' }, { id: 'epicgames', domain: 'epicgames.com' }, { id: 'riotgames', domain: 'riotgames.com' },
    { id: 'skydance', domain: 'skydance.com' }, { id: 'pocketgems', domain: 'pocketgems.com' }, { id: 'groq', domain: 'groq.com' }, // LPU чипы, сейчас на хайпе
    { id: 'together', domain: 'together.ai' }, // Облако для GPU
    { id: 'langchain', domain: 'langchain.com' }, // Фреймворк для LLM
    { id: 'pinecone', domain: 'pinecone.io' }, // Векторные БД
    { id: 'weaviate', domain: 'weaviate.io' },
    { id: 'midjourney', domain: 'midjourney.com' },
    { id: 'coreweave', domain: 'coreweave.com' }, // Масштабирование GPU
    { id: 'modal', domain: 'modal.com' }, // Serverless для ML
    { id: 'adyen', domain: 'adyen.com' },
    { id: 'wise', domain: 'wise.com' },
    { id: 'nu-bank', domain: 'nubank.com.br' },
    { id: 'e-toro', domain: 'etoro.com' },
    { id: 'checkout', domain: 'checkout.com' },
    { id: 'marqeta', domain: 'marqeta.com' },
    { id: 'ledger', domain: 'ledger.com' },
    { id: 'prisma', domain: 'prisma.io' },
    { id: 'astro', domain: 'astro.build' },
    { id: 'turo', domain: 'turo.com' },
    { id: 'grafana', domain: 'grafana.com' },
    { id: 'posthog', domain: 'posthog.com' }, // Open-source аналитика
    { id: 'logrocket', domain: 'logrocket.com' },
    { id: 'linear', domain: 'linear.app' },
    { id: 'nvidia', domain: 'nvidia.com' },
    { id: 'apple', domain: 'apple.com' },
    { id: 'netflix', domain: 'netflix.com' },
    { id: 'meta', domain: 'meta.com' },
    { id: 'google', domain: 'google.com' },
    { id: 'microsoft', domain: 'microsoft.com' },
    { id: 'amazon', domain: 'amazon.jobs' },
    { id: 'adaptive-ml', domain: 'adaptive-ml.com' },
    { id: 'reka', domain: 'reka.ai' },
    { id: 'cognition', domain: 'cognition.ai' }, // Тот самый Devin
    { id: 'phind', domain: 'phind.com' },
    { id: 'perceptual', domain: 'perceptual.ai' },
    { id: 'langsmith', domain: 'langchain.com' },
    { id: 'deepgram', domain: 'deepgram.com' },
    { id: 'assemblyai', domain: 'assemblyai.com' },
    { id: 'baseten', domain: 'baseten.co' },
    { id: 'replicate', domain: 'replicate.com' },{ id: 'coolify', domain: 'coolify.io' },
    { id: 'tursodb', domain: 'turso.tech' },
    { id: 'edgedb', domain: 'edgedb.com' },
    { id: 'convex', domain: 'convex.dev' },
    { id: 'sst', domain: 'sst.dev' },
    { id: 'clerk', domain: 'clerk.com' },
    { id: 'kinde', domain: 'kinde.com' },
    { id: 'workos', domain: 'workos.com' },
    { id: 'svix', domain: 'svix.com' },
    { id: 'inngest', domain: 'inngest.com' },
    { id: 'mercury', domain: 'mercury.com' }, // Банк для стартапов
    { id: 'brex', domain: 'brex.com' },
    { id: 'arc', domain: 'arc.tech' },
    { id: 'modern-treasury', domain: 'moderntreasury.com' },
    { id: 'paddle', domain: 'paddle.com' },
    { id: 'lemon-squeezy', domain: 'lemonsqueezy.com' },
    { id: 'trolley', domain: 'trolley.com' },
    { id: 'tally', domain: 'tally.so' },
    { id: 'chainguard', domain: 'chainguard.dev' },
    { id: 'teleport', domain: 'goteleport.com' },
    { id: 'boundary', domain: 'boundary.com' },
    { id: 'incident-io', domain: 'incident.io' },
    { id: 'checkly', domain: 'checklyhq.com' },
    { id: 'openai', domain: 'openai.com' },
    { id: 'anthropic', domain: 'anthropic.com' },
    { id: 'perplexity', domain: 'perplexity.ai' },
    { id: 'mistral', domain: 'mistral.ai' },
    { id: 'cohere', domain: 'cohere.com' },
    { id: 'huggingface', domain: 'huggingface.co' },
    { id: 'elevenlabs', domain: 'elevenlabs.io' },
    { id: 'characterai', domain: 'character.ai' },
    { id: 'pika', domain: 'pika.art' },
    { id: 'runway', domain: 'runwayml.com' },
    { id: 'midjourney', domain: 'midjourney.com' },
    { id: 'scale', domain: 'scale.com' },
    { id: 'anduril', domain: 'anduril.com' },
    { id: 'groq', domain: 'groq.com' },
    { id: 'cognition', domain: 'cognition.ai' },
    { id: 'together', domain: 'together.ai' },

    // --- ELITE DEVTOOLS & INFRA ---
    { id: 'vercel', domain: 'vercel.com' },
    { id: 'stripe', domain: 'stripe.com' },
    { id: 'figma', domain: 'figma.com' },
    { id: 'supabase', domain: 'supabase.com' },
    { id: 'planetscale', domain: 'planetscale.com' },
    { id: 'clerk', domain: 'clerk.com' },
    { id: 'resend', domain: 'resend.com' },
    { id: 'linear', domain: 'linear.app' },
    { id: 'notion', domain: 'notion.so' },
    { id: 'github', domain: 'github.com' },
    { id: 'gitlab', domain: 'about.gitlab.com' },
    { id: 'sentry', domain: 'sentry.io' },
    { id: 'postman', domain: 'postman.com' },
    { id: 'auth0', domain: 'auth0.com' },
    { id: 'okta', domain: 'okta.com' },
    { id: 'cloudflare', domain: 'cloudflare.com' },
    { id: 'digitalocean', domain: 'digitalocean.com' },
    { id: 'netlify', domain: 'netlify.com' },
    { id: 'railway', domain: 'railway.app' },
    { id: 'neon', domain: 'neon.tech' },
    { id: 'upstash', domain: 'upstash.com' },
    { id: 'flyio', domain: 'fly.io' },
    { id: 'prisma', domain: 'prisma.io' },
    { id: 'astro', domain: 'astro.build' },

    // --- FINTECH & CRYPTO ---
    { id: 'revolut', domain: 'revolut.com' },
    { id: 'monzo', domain: 'monzo.com' },
    { id: 'robinhood', domain: 'robinhood.com' },
    { id: 'coinbase', domain: 'coinbase.com' },
    { id: 'kraken', domain: 'kraken.com' },
    { id: 'plaid', domain: 'plaid.com' },
    { id: 'brex', domain: 'brex.com' },
    { id: 'ramp', domain: 'ramp.com' },
    { id: 'affirm', domain: 'affirm.com' },
    { id: 'klarna', domain: 'klarna.com' },
    { id: 'sofi', domain: 'sofi.com' },
    { id: 'mercury', domain: 'mercury.com' },
    { id: 'alchemy', domain: 'alchemy.com' },
    { id: 'chainlink', domain: 'chain.link' },
    { id: 'fireblocks', domain: 'fireblocks.com' },

    // --- TOP STARTUPS & UNICORNS ---
    { id: 'uber', domain: 'uber.com' },
    { id: 'airbnb', domain: 'airbnb.com' },
    { id: 'discord', domain: 'discord.com' },
    { id: 'shopify', domain: 'shopify.com' },
    { id: 'slack', domain: 'slack.com' },
    { id: 'canva', domain: 'canva.com' },
    { id: 'miro', domain: 'miro.com' },
    { id: 'loom', domain: 'loom.com' },
    { id: 'zapier', domain: 'zapier.com' },
    { id: 'airtable', domain: 'airtable.com' },
    { id: 'webflow', domain: 'webflow.com' },
    { id: 'framer', domain: 'framer.com' },
    { id: 'deel', domain: 'deel.com' },
    { id: 'remote', domain: 'remote.com' },
    { id: 'wiz', domain: 'wiz.io' },
    { id: 'snyk', domain: 'snyk.io' },
    { id: 'vanta', domain: 'vanta.com' },
    { id: 'drata', domain: 'drata.com' },
    { id: 'samsara', domain: 'samsara.com' },
    { id: 'verkada', domain: 'verkada.com' },
    { id: 'grammarly', domain: 'grammarly.com' },
    { id: 'reddit', domain: 'reddit.com' },
    { id: 'instacart', domain: 'instacart.com' },
    { id: 'doordash', domain: 'doordash.com' },
    { id: 'lyft', domain: 'lyft.com' },
    // --- BIG TECH & ENTERPRISE ---
    { id: "google", domain: "google.com" },
    { id: "microsoft", domain: "microsoft.com" },
    { id: "meta", domain: "meta.com" },
    { id: "amazon", domain: "amazon.com" },
    { id: "apple", domain: "apple.com" },
    { id: "netflix", domain: "netflix.com" },
    { id: "nvidia", domain: "nvidia.com" },
    { id: "salesforce", domain: "salesforce.com" },
    { id: "adobe", domain: "adobe.com" },
    { id: "oracle", domain: "oracle.com" },
    { id: "sap", domain: "sap.com" },
    { id: "ibm", domain: "ibm.com" },
    { id: "intel", domain: "intel.com" },
    { id: "cisco", domain: "cisco.com" },
    { id: "vmware", domain: "vmware.com" },
    { id: "servicenow", domain: "servicenow.com" },
    { id: "atlassian", domain: "atlassian.com" },
    { id: "shopify", domain: "shopify.com" },
    { id: "uber", domain: "uber.com" },
    { id: "airbnb", domain: "airbnb.com" },
    { id: "snowflake", domain: "snowflake.com" },
    { id: "databricks", domain: "databricks.com" },
    { id: "palantir", domain: "palantir.com" },
    { id: "autodesk", domain: "autodesk.com" },
    { id: "workday", domain: "workday.com" },
    { id: "intuit", domain: "intuit.com" },
    { id: "squareup", domain: "squareup.com" },
    { id: "zoom", domain: "zoom.us" },
    { id: "slack", domain: "slack.com" },
    { id: "spotify", domain: "spotify.com" },
    { id: "twitter", domain: "twitter.com" },
    { id: "lyft", domain: "lyft.com" },
    { id: "doordash", domain: "doordash.com" },
    { id: "instacart", domain: "instacart.com" },
    { id: "pinterest", domain: "pinterest.com" },
    { id: "snapchat", domain: "snapchat.com" },
    { id: "roblox", domain: "roblox.com" },
    { id: "dropbox", domain: "dropbox.com" },
    { id: "box", domain: "box.com" },
    { id: "hubspot", domain: "hubspot.com" },
    { id: "zendesk", domain: "zendesk.com" },
    { id: "zoominfo", domain: "zoominfo.com" },
    { id: "twilio", domain: "twilio.com" },

    // --- INFRA & CYBERSECURITY ---
    { id: "cloudflare", domain: "cloudflare.com" },
    { id: "paloaltonetworks", domain: "paloaltonetworks.com" },
    { id: "fortinet", domain: "fortinet.com" },
    { id: "crowdstrike", domain: "crowdstrike.com" },
    { id: "zscaler", domain: "zscaler.com" },
    { id: "okta", domain: "okta.com" },
    { id: "splunk", domain: "splunk.com" },
    { id: "cloudera", domain: "cloudera.com" },
    { id: "teradata", domain: "teradata.com" },
    { id: "microstrategy", domain: "microstrategy.com" },
    { id: "akamai", domain: "akamai.com" },
    { id: "f5", domain: "f5.com" },
    { id: "juniper", domain: "juniper.net" },
    { id: "arista", domain: "arista.com" },
    { id: "hpe", domain: "hpe.com" },
    { id: "dell", domain: "dell.com" },
    { id: "lenovo", domain: "lenovo.com" },
    { id: "sony", domain: "sony.com" },
    { id: "samsung", domain: "samsung.com" },
    { id: "lg", domain: "lg.com" },
    { id: "panasonic", domain: "panasonic.com" },
    { id: "toshiba", domain: "toshiba.com" },
    { id: "sentinelone", domain: "sentinelone.com" },
    { id: "cybereason", domain: "cybereason.com" },
    { id: "tanium", domain: "tanium.com" },
    { id: "darktrace", domain: "darktrace.com" },
    { id: "fireeye", domain: "fireeye.com" },
    { id: "mcafee", domain: "mcafee.com" },
    { id: "norton", domain: "norton.com" },
    { id: "kaspersky", domain: "kaspersky.com" },
    { id: "bitdefender", domain: "bitdefender.com" },
    { id: "trendmicro", domain: "trendmicro.com" },
    { id: "avast", domain: "avast.com" },
    { id: "avg", domain: "avg.com" },
    { id: "malwarebytes", domain: "malwarebytes.com" },
    { id: "checkpoint", domain: "checkpoint.com" },
    { id: "netskope", domain: "netskope.com" },
    { id: "fastly", domain: "fastly.com" },
    { id: "imperva", domain: "imperva.com" },
    { id: "barracuda", domain: "barracuda.com" },
    { id: "proofpoint", domain: "proofpoint.com" },
    { id: "mimecast", domain: "mimecast.com" },
    { id: "knowbe4", domain: "knowbe4.com" },
    { id: "oneidentity", domain: "oneidentity.com" },
    { id: "sailpoint", domain: "sailpoint.com" },
    { id: "cyberark", domain: "cyberark.com" },
    { id: "beyondtrust", domain: "beyondtrust.com" },
    { id: "thycotic", domain: "thycotic.com" },
    { id: "pingidentity", domain: "pingidentity.com" },
    { id: "forgerock", domain: "forgerock.com" },

    // --- FINTECH & CRYPTO ---
    { id: "stripe", domain: "stripe.com" },
    { id: "revolut", domain: "revolut.com" },
    { id: "monzo", domain: "monzo.com" },
    { id: "wise", domain: "wise.com" },
    { id: "klarna", domain: "klarna.com" },
    { id: "affirm", domain: "affirm.com" },
    { id: "plaid", domain: "plaid.com" },
    { id: "brex", domain: "brex.com" },
    { id: "ramp", domain: "ramp.com" },
    { id: "mercury", domain: "mercury.com" },
    { id: "deel", domain: "deel.com" },
    { id: "remote", domain: "remote.com" },
    { id: "rippling", domain: "rippling.com" },
    { id: "gusto", domain: "gusto.com" },
    { id: "zenefits", domain: "zenefits.com" },
    { id: "checkout", domain: "checkout.com" },
    { id: "adyen", domain: "adyen.com" },
    { id: "bolt", domain: "bolt.com" },
    { id: "chime", domain: "chime.com" },
    { id: "sofi", domain: "sofi.com" },
    { id: "robinhood", domain: "robinhood.com" },
    { id: "coinbase", domain: "coinbase.com" },
    { id: "kraken", domain: "kraken.com" },
    { id: "gemini", domain: "gemini.com" },
    { id: "blockchain", domain: "blockchain.com" },
    { id: "alchemy", domain: "alchemy.com" },
    { id: "chainlink", domain: "chainlink.com" },
    { id: "fireblocks", domain: "fireblocks.com" },
    { id: "ledger", domain: "ledger.com" },
    { id: "consensys", domain: "consensys.net" },
    { id: "polygon", domain: "polygon.technology" },
    { id: "solana", domain: "solana.com" },
    { id: "circle", domain: "circle.com" },
    { id: "paxos", domain: "paxos.com" },
    { id: "tether", domain: "tether.to" },
    { id: "bitpanda", domain: "bitpanda.com" },
    { id: "etoro", domain: "etoro.com" },
    { id: "public", domain: "public.com" },
    { id: "wealthfront", domain: "wealthfront.com" },
    { id: "betterment", domain: "betterment.com" },
    { id: "stash", domain: "stash.com" },
    { id: "acorns", domain: "acorns.com" },
    { id: "digit", domain: "digit.co" },
    { id: "dave", domain: "dave.com" },
    { id: "moneygram", domain: "moneygram.com" },
    { id: "westernunion", domain: "westernunion.com" },

    // --- AI & MACHINE LEARNING ---
    { id: "openai", domain: "openai.com" },
    { id: "anthropic", domain: "anthropic.com" },
    { id: "perplexity", domain: "perplexity.ai" },
    { id: "mistral", domain: "mistral.ai" },
    { id: "cohere", domain: "cohere.com" },
    { id: "huggingface", domain: "huggingface.co" },
    { id: "elevenlabs", domain: "elevenlabs.io" },
    { id: "character", domain: "character.ai" },
    { id: "pika", domain: "pika.art" },
    { id: "runwayml", domain: "runwayml.com" },
    { id: "midjourney", domain: "midjourney.com" },
    { id: "scale", domain: "scale.com" },
    { id: "groq", domain: "groq.com" },
    { id: "cognition", domain: "cognition.ai" },
    { id: "together", domain: "together.ai" },
    { id: "pinecone", domain: "pinecone.io" },
    { id: "weaviate", domain: "weaviate.io" },
    { id: "langchain", domain: "langchain.com" },
    { id: "replicate", domain: "replicate.com" },
    { id: "modal", domain: "modal.com" },
    { id: "glean", domain: "glean.com" },
    { id: "tome", domain: "tome.app" },
    { id: "jasper", domain: "jasper.ai" },
    { id: "copy", domain: "copy.ai" },
    { id: "writesonic", domain: "writesonic.com" },
    { id: "descript", domain: "descript.com" },
    { id: "synthesia", domain: "synthesia.io" },
    { id: "deepl", domain: "deepl.com" },
    { id: "grammarly", domain: "grammarly.com" },
    { id: "otter", domain: "otter.ai" },

    // --- SAAS & TOOLS ---
    { id: "notion", domain: "notion.so" },
    { id: "linear", domain: "linear.app" },
    { id: "asana", domain: "asana.com" },
    { id: "monday", domain: "monday.com" },
    { id: "miro", domain: "miro.com" },
    { id: "figma", domain: "figma.com" },
    { id: "canva", domain: "canva.com" },
    { id: "webflow", domain: "webflow.com" },
    { id: "framer", domain: "framer.com" },
    { id: "zapier", domain: "zapier.com" },
    { id: "airtable", domain: "airtable.com" },
    { id: "intercom", domain: "intercom.com" },
    { id: "gong", domain: "gong.io" },
    { id: "chorus", domain: "chorus.ai" },
    { id: "outreach", domain: "outreach.io" },
    { id: "salesloft", domain: "salesloft.com" },
    { id: "drift", domain: "drift.com" },
    { id: "insider", domain: "insider.com" },
    { id: "braze", domain: "braze.com" },
    { id: "iterable", domain: "iterable.com" },
    { id: "customer", domain: "customer.io" },

    // --- DEVTOOLS & DATA ---
    { id: "snyk", domain: "snyk.io" },
    { id: "wiz", domain: "wiz.io" },
    { id: "vanta", domain: "vanta.com" },
    { id: "drata", domain: "drata.com" },
    { id: "segment", domain: "segment.com" },
    { id: "mparticle", domain: "mparticle.com" },
    { id: "amplitude", domain: "amplitude.com" },
    { id: "mixpanel", domain: "mixpanel.com" },
    { id: "heap", domain: "heap.io" },
    { id: "pendo", domain: "pendo.io" },
    { id: "fullstory", domain: "fullstory.com" },
    { id: "logrocket", domain: "logrocket.com" },
    { id: "sentry", domain: "sentry.io" },
    { id: "honeycomb", domain: "honeycomb.io" },
    { id: "lightstep", domain: "lightstep.com" },
    { id: "newrelic", domain: "newrelic.com" },
    { id: "dynatrace", domain: "dynatrace.com" },
    { id: "datadoghq", domain: "datadoghq.com" },
    { id: "grafana", domain: "grafana.com" },
    { id: "influxdata", domain: "influxdata.com" },
    { id: "timescale", domain: "timescale.com" },
    { id: "cockroachlabs", domain: "cockroachlabs.com" },
    { id: "yugabyte", domain: "yugabyte.com" },
    { id: "planetscale", domain: "planetscale.com" },
    { id: "supabase", domain: "supabase.com" },
    { id: "appwrite", domain: "appwrite.io" },
    { id: "hasura", domain: "hasura.io" },
    { id: "prisma", domain: "prisma.io" },
    { id: "edgedb", domain: "edgedb.com" },
    { id: "surrealdb", domain: "surrealdb.com" },
    { id: "turso", domain: "turso.tech" },
    { id: "neon", domain: "neon.tech" },
    { id: "upstash", domain: "upstash.com" },
    { id: "railway", domain: "railway.app" },
    { id: "fly", domain: "fly.io" },
    { id: "render", domain: "render.com" },
    { id: "digitalocean", domain: "digitalocean.com" },
    { id: "linode", domain: "linode.com" },
    { id: "vultr", domain: "vultr.com" },
    { id: "ovhcloud", domain: "ovhcloud.com" },
    { id: "hetzner", domain: "hetzner.com" },
    { id: "scw", domain: "scw.cloud" },
    { id: "auth0", domain: "auth0.com" },
    { id: "clerk", domain: "clerk.com" },
    { id: "stytch", domain: "stytch.com" },
    { id: "kinde", domain: "kinde.com" },
    { id: "workos", domain: "workos.com" },
    { id: "secureframe", domain: "secureframe.com" },
    { id: "laika", domain: "laika.com" },
    { id: "thoropass", domain: "thoropass.com" },
    { id: "complyadvantage", domain: "complyadvantage.com" },
    { id: "chainalysis", domain: "chainalysis.com" },
    { id: "elliptic", domain: "elliptic.co" },
    { id: "trmlabs", domain: "trmlabs.com" },
    { id: "coinfirm", domain: "coinfirm.com" }
];
